# dga/keygas.py
from __future__ import annotations

import logging

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


# ============================================================
# SAFE GAS
# ============================================================

def _gas(row: pd.Series, name: str) -> float:
    """
    Safely read a gas concentration.

    Missing / invalid / non-finite / negative values are treated
    as NaN.

    Do not silently convert missing laboratory measurements to
    0 ppm.
    """

    value = row.get(name, np.nan)

    try:
        value = float(value)
    except (TypeError, ValueError):
        return np.nan

    if not np.isfinite(value) or value < 0:
        return np.nan

    return value


# ============================================================
# TDCG
# ============================================================

def _safe_tdcg(row: pd.Series) -> float:
    """
    Calculate TDCG from the six combustible gases.

    TDCG =
        H2 + CH4 + C2H6 + C2H4 + C2H2 + CO

    CO2 is not included.

    This is a reporting/normalization value only.

    It is NOT used as a universal IEEE C57.104-2019
    fault/normal threshold.
    """

    value = row.get("tdcg", np.nan)

    try:
        value = float(value)
    except (TypeError, ValueError):
        value = np.nan

    if np.isfinite(value) and value >= 0:
        return value

    gas_names = [
        "h2",
        "ch4",
        "c2h6",
        "c2h4",
        "c2h2",
        "co",
    ]

    values = [
        _gas(row, gas)
        for gas in gas_names
    ]

    if not all(np.isfinite(value) for value in values):
        return np.nan

    return float(sum(values))


# ============================================================
# VALIDITY
# ============================================================

def _all_required_gases_present(row: pd.Series) -> bool:
    required = [
        "h2",
        "ch4",
        "c2h6",
        "c2h4",
        "c2h2",
        "co",
    ]

    return all(
        np.isfinite(_gas(row, gas))
        for gas in required
    )


# ============================================================
# KEY GAS METHOD
# ============================================================

def key_gas_method(row: pd.Series) -> str:
    """
    IEEE C57.104-2019 Annex D.1 Key Gas Method.

    Principal key-gas patterns:

        C2H4
            -> Thermal mineral oil

        CO
            -> Thermal mineral oil + cellulose

        H2
            -> Electrical low-energy partial discharge

        H2 + C2H2
            -> Electrical high-energy discharge / arcing

    NORMAL is NOT generated by this method.

    ABSTAIN means the key-gas pattern is not sufficiently clear.

    This is intentionally a screening/supporting method and should
    not override IEC ratio, Rogers, Duval or other stronger
    diagnostic methods.
    """

    if not _all_required_gases_present(row):
        return "ABSTAIN"

    h2 = _gas(row, "h2")
    ch4 = _gas(row, "ch4")
    c2h6 = _gas(row, "c2h6")
    c2h4 = _gas(row, "c2h4")
    c2h2 = _gas(row, "c2h2")
    co = _gas(row, "co")

    combustible = {
        "h2": h2,
        "ch4": ch4,
        "c2h6": c2h6,
        "c2h4": c2h4,
        "c2h2": c2h2,
        "co": co,
    }

    total = float(
        sum(combustible.values())
    )

    if total <= 0:
        return "ABSTAIN"

    # ========================================================
    # Convert to approximate TCG proportions.
    #
    # This is used only to establish "predominance"; IEEE's
    # Annex D describes patterns qualitatively rather than
    # prescribing one universal hard percentage threshold.
    # ========================================================

    proportions = {
        gas: value / total
        for gas, value in combustible.items()
    }

    # ========================================================
    # High-energy electrical discharge
    #
    # Key combination:
    #     H2 + C2H2
    #
    # Acetylene is the characteristic high-energy electrical
    # discharge indicator.
    #
    # We require both gases to be materially present and avoid
    # classifying a trace acetylene measurement as arcing.
    # ========================================================

    if c2h2 > 0 and h2 > 0:

        c2h2_fraction = proportions["c2h2"]
        h2_fraction = proportions["h2"]

        if (
            c2h2_fraction >= 0.05
            and h2_fraction >= 0.20
        ):
            return "D2"

    # ========================================================
    # Hydrogen-dominant pattern
    #
    # Low-energy PD:
    # predominantly H2 with small quantities of hydrocarbons.
    #
    # H2 needs to be the principal combustible gas.
    # ========================================================

    hydrocarbon_total = (
        ch4
        + c2h6
        + c2h4
        + c2h2
    )

    if h2 > 0:

        h2_fraction = proportions["h2"]

        if (
            h2_fraction >= 0.60
            and h2 >= hydrocarbon_total
        ):
            # Avoid confusing substantial acetylene with PD.
            if c2h2 <= 0.10 * h2:
                return "PD"

    # ========================================================
    # CO-dominant pattern
    #
    # IEEE:
    #     CO -> thermal mineral oil and cellulose
    #
    # CO is NOT sufficient merely because it exceeds some
    # arbitrary ppm threshold. It must be the principal gas
    # pattern.
    # ========================================================

    hydrocarbon_plus_h2 = (
        h2
        + ch4
        + c2h6
        + c2h4
        + c2h2
    )

    if co > 0:

        co_fraction = proportions["co"]

        if (
            co_fraction >= 0.60
            and co >= hydrocarbon_plus_h2
        ):
            return "THERMAL_CELLULOSE"

    # ========================================================
    # Ethylene-dominant thermal oil pattern
    #
    # IEEE:
    #     Predominantly C2H4 with smaller quantities of
    #     C2H6, CH4 and H2.
    #
    # Do not fabricate T1/T2/T3 from Key Gas. The Key Gas method
    # itself provides "thermal mineral oil", not temperature
    # classes.
    # ========================================================

    thermal_companions = (
        c2h6
        + ch4
        + h2
    )

    if c2h4 > 0:

        c2h4_fraction = proportions["c2h4"]

        if (
            c2h4_fraction >= 0.50
            and c2h4 >= thermal_companions
            and c2h2 <= 0.10 * c2h4
        ):
            return "THERMAL_OIL"

    # ========================================================
    # No sufficiently clear principal-gas pattern.
    # ========================================================

    return "ABSTAIN"


# ============================================================
# DATAFRAME APPLICATION
# ============================================================

def apply_key_gas(
    df: pd.DataFrame,
) -> pd.DataFrame:

    df = df.copy()

    df["keygas_fault"] = df.apply(
        key_gas_method,
        axis=1,
    )

    if "tdcg" not in df.columns:
        df["tdcg"] = df.apply(
            _safe_tdcg,
            axis=1,
        )

    logger.debug(
        "IEEE C57.104-2019 Key Gas diagnostic applied."
    )

    if logger.isEnabledFor(logging.DEBUG):

        sample_cols = [
            "h2",
            "ch4",
            "c2h6",
            "c2h4",
            "c2h2",
            "co",
            "co2",
            "tdcg",
            "keygas_fault",
        ]

        available_cols = [
            col
            for col in sample_cols
            if col in df.columns
        ]

        logger.debug(
            "Sample Key Gas results:\n%s",
            df[available_cols]
            .head(5)
            .to_string(),
        )

    return df